---
AllCops:
  TargetRubyVersion: 2.6
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Max: 50
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 11
NumericLiterals:
  MinDigits: 10
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': ()
    '%q': '{}'
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '{}'
    '%W': ()
    '%x': ()
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Layout/HeredocIndentation:
  Enabled: false
Layout/ClosingHeredocIndentation:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RegexpLiteral:
  Enabled: false
